repos:
  # -------------------------------
  # Core hygiene checks
  # -------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: name-tests-test
        args: ['--pytest-test-first']

  # -------------------------------
  # Code formatting (standard)
  # -------------------------------
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # -------------------------------
  # Linting
  # -------------------------------
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  # -------------------------------
  # Type checking
  # -------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [types-pyyaml]
        exclude: ^testing/resources/

  # -------------------------------
  # Security - Bandit (fast, local)
  # -------------------------------
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-ll", "-iii"]
        exclude: tests/

  # -------------------------------
  # Security - pip-audit (dependencies)
  # -------------------------------
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
        args: ["-r", "requirements.txt",
         "--ignore-vuln", "GHSA-jr27-m4p2-rc6r",
         "--ignore-vuln", "GHSA-wj6h-64fc-37mp"]

  # -------------------------------
  # Security - Semgrep (advanced)
  # -------------------------------
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.75.0
    hooks:
      - id: semgrep
        args: ["--config=auto"]

   # Secrets detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
